sumirow/freemarket_sample_56c

Gemfile
config/database.yml

データベースをSQLiteからMySQLに変更
カリキュラムで使い慣れたMySQLで開発を進めるため

Change the database from sqlite to mysql

---

app/assets/stylesheets/new.scss
app/views/devise/sessions/new.html.haml

[WHAT]
BEM記法で書き直しました。
[WHY]
HTMLからHamlに修正する際、BEM記法に修正するのを失念していた為。

[WIP] Updated BEM for login page

---

app/assets/javascripts/users.coffee
app/assets/stylesheets/sign_out.scss
app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/helpers/users_helper.rb
app/views/users/sign_out.html.haml
config/routes.rb
db/schema.rb
test/controllers/users_controller_test.rb

[WHAT]
ログアウト画面をアップデートしました。
https://gyazo.com/383c344314d67449a178cb9423db1ab3
[WHY]
ログアウトする為。

Updated logout view

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/new.scss
app/views/devise/sessions/new.html.haml
app/views/devise/shared/_links.html.haml

コンフリクト解決時に変更されてしまったファイルを復元
その際に表示が正しく復元されなかったところ（リセットCSSの違いによる影響？）を修正
ローカルでは正しく表示されていた部分をmasterブランチのコードにも反映させるため

Fix sign in view

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/module/_product_new.scss
app/assets/stylesheets/module/show.scss
app/assets/stylesheets/products.scss
app/views/products/new.html.haml
app/views/products/show.html.haml
app/views/users/show.html.haml

#WHAT
全体に影響を及ぼしているCSSがあったので、修正しました。
また、クラス名が被ってビューが崩れているところがあったので、それも修正しました。
iconが表示されない問題も解消しました。
#WHY
統合した際に全体のビューが崩れていた為。

[WIP]Fixed CSS

---

config/unicorn.rb

WHAT
unicorn.rbの修正
WHY
Nginxの設定の為

fix unicorn.rb

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb
config/environments/production.rb
config/unicorn.rb

WHAT
自動デプロイに必要な設定ファイルの編集
WHY
自動デプロイの為

auto-deploy setting

---

app/assets/stylesheets/module/_new.scss
app/assets/stylesheets/module/_product_new.scss
app/assets/stylesheets/module/mypage.scss
app/views/products/new.html.haml
config/routes.rb

#WHAT
全ページに影響を及ぼしていたCSSを修正した。
また、そのCSSが適用された上で他のページが作成されていた為、上記問題を解消した際の全ページのCSSを修正した。
#WHY
全ページのビューが崩れていた為。

[WIP] Fixed bugs of CSS of all pages

---

app/views/products/index.html.haml
app/views/products/show.html.haml
app/views/users/mypage.html.haml
app/views/users/show.html.haml
app/views/users/sign_out.html.haml

ヘッダー/フッターが必要なところにrenderでパーシャル呼び出し
正しく表示するため

Apply render partials

---

app/assets/stylesheets/user_sign_ups/address.scss
app/assets/stylesheets/user_sign_ups/complete.scss
app/assets/stylesheets/user_sign_ups/header.scss
app/assets/stylesheets/user_sign_ups/infomation.scss
app/assets/stylesheets/user_sign_ups/payment.scss

user 新規登録addressページのview崩れ修正しました。
user 新規登録paymentページのview崩れ修正しました。
user 新規登録completeページのview崩れ修正しました。 
user 新規登録informationページのview崩れ修正しました。 
user 新規登録headerのview崩れ修正しました。 
任意欄、必須欄の修正
各所著しいviewの崩れ箇所
view調整し、コードレビューに備えるため
https://gyazo.com/4efef2332f0f4f42a27ee47cd628692f
https://gyazo.com/77a029b8af95e7d49ba46c43c777638b
https://gyazo.com/2b9affb65fadbfe5be9bb2ada9189846
https://gyazo.com/9085b2ff4850fed61c351f5353b6e84f
https://gyazo.com/8e2d9d6e94aa98834121a7bd5d800992
https://gyazo.com/8a3cfea98797c3b6fb19defc90cab0e3
https://gyazo.com/8953176023c29f2e88a47b8f5e90ba50

fix users address page

---

app/assets/stylesheets/application.scss

#WHAT
Updated error
#WHY
Because there was an error

Updated error

---

app/assets/stylesheets/module/new_user_registration.scss
app/assets/stylesheets/user_sign_ups/header.scss
app/views/devise/registrations/new.html.haml

WHAT
サインアップ時のビュー画面の修正
WHY
ビューの崩れの為

Fix user sign up view2

---

app/views/products/new.html.haml

WHAT
自動デプロイが反映されているかのテストの為
WHY
自動デプロイが反映されているかのテストの為

deploy-test1

---

app/assets/stylesheets/module/_credit_confirmation.scss
app/assets/stylesheets/module/_sign_out.scss
app/assets/stylesheets/module/show.scss
app/assets/stylesheets/purchase.scss
app/assets/stylesheets/shared/exhibitation.scss
app/assets/stylesheets/shared/header.scss
app/assets/stylesheets/user_sign_ups/header.scss
app/assets/stylesheets/user_sign_ups/payment.scss
app/assets/stylesheets/user_sign_ups/sms_confirmation.scss
app/views/purchase/show.html.haml
app/views/users/sign_out.html.haml

各ページのview崩れを修正
見た目、見栄えを整えるため
https://gyazo.com/770a9f08b5b88a28bf2a5dd7d919c2d4                                      /users/mypage
https://gyazo.com/3cc218e61db0ce994867000100dc09b3                                    /users/sign_out
https://gyazo.com/29075bf58926af25f77c6d98c366a6ce                          /users/sms_confirmation
https://gyazo.com/0a506170712828da3919a4a510de5b90                                   /users/address
https://gyazo.com/706612431e66bd86d95b5865d7d0adf6                                 /users/payment
https://gyazo.com/f8e78cc42eb658806d0b81e6d078519b                                 /users/complete
https://gyazo.com/ef57022e02be8d51684d3e15db0e1c58                                  /users/information
https://gyazo.com/7ec3eb1d347abf538d4c2ead9863fc26 …

modificate view

---

Gemfile.lock
app/controllers/products_controller.rb
app/models/image.rb
app/models/product.rb
app/views/products/new.html.haml
db/schema.rb

WHAT
画像投稿機能に関してproductモデルに紐付いた投稿ができるようにした
WHY
１つのフォームで２つのモデルを扱いたい為

Add image form

---

Gemfile
Gemfile.lock
app/controllers/users/omniauth_callbacks_controller.rb
app/models/user.rb
app/views/devise/sessions/new.html.haml
config/initializers/devise.rb
db/schema.rb

#WHAT
FacebookとGoogleのログイン認証機能を作りました。
#WHY
Mercariに実装されている為。

[WIP] Created SNS login

---

db/seeds.rb

本番環境でtestするため
seedsファイルでデータベースに初期値を入れた。

test seeds file

---

db/seeds.rb

コメントアウトすべき場所を削除した。
本番環境でseedsデータが反映できるかテストを行う

fix seeds file for test

---

db/migrate/20190810081052_add__info_columns_to_users.rb
db/migrate/20190814115538_rename_prefecture_column_to_addresses.rb

マイグレーションファイルの整合性を取るためにファイルを再作成・削除
マイグレーション実行時にコンフリクトが起きたのでそれを解消するため

Change migration files

---

app/views/devise/sessions/new.html.haml

#WHAT
CSSを修正しました。
https://gyazo.com/16314ffcc4016bf7c0e3947a548db2b6
#WHY
文字の色の修正が漏れていた為。

Updated CSS for login

---

db/seeds.rb

本番環境のテストのため
image サンプルをseed fileに投入

set image sample

---

config/initializers/devise.rb

#WHAT
SNS認証に関わるdevise.rbのコードを修正しました。
#WHY
SNS認証がうまくいっていなかった為。

Updated sns confirmation

---

app/assets/stylesheets/module/_product_new.scss
app/views/products/new.html.haml

WHAT
出品ページのビューの修正
WHY
サーバーサイドでの実装の際に一部ビューが崩れた部分があり、その修正の為
参考動画
https://gyazo.com/ac2af69f524bc0ac685057298d741bd9

Fix exhibition veiw

---

app/controllers/users_controller.rb

コメントアウトの削除
不要なコメントアウトがコードに残っていると可視性が低くなるため

Delete comment out

---

.gitignore
app/controllers/products_controller.rb

WHAT
出品後のパスの修正
WHY
出品が出来ない際の挙動がおかしい為

Exihibition ajax

---

app/controllers/users_controller.rb
app/views/users/address.html.haml
app/views/users/complete.html.haml
app/views/users/payment.html.haml
app/views/users/sms_confirmation.html.haml

ユーザー新規登録機能のデバッグ
他機能を実装する際にユーザー新規登録機能におけるバグを発見したため

Fix user signup function

---

.gitignore
app/assets/stylesheets/products.scss
app/controllers/products_controller.rb
app/views/products/new.html.haml
app/views/products/show.html.haml

条件分岐によってビューの表示を変更
ログイン時と非ログイン時で表示させるべき情報が異なるため
- ログイン時（出品者とログインユーザーが一致しているとき）
https://gyazo.com/3aa439cc407dfab483b59d6abaa6a73a
- 非ログイン時
https://gyazo.com/c7e921b495a04cef62c008d330c4b40d
- ユーザーのその他の出品・同カテゴリーの商品の表示があるとき
https://gyazo.com/a5484085849a08ede530095a925a2365

Improve products show page

---

app/views/products/show.html.haml

商品詳細画面の表示を調整
商品詳細画面のviewを整え。コードレビューに備えるため

Adjust view

---

README.md
db/migrate/20190823110619_rename_brand_id_column_to_brand.rb
db/migrate/20190823111256_change_datatype_brand_of_products.rb
db/migrate/20190823111721_change_column_to_allow_null.rb
db/schema.rb

#WHAT
DBを修正しました。
具体的には、brand_id(integer, null:false )からbrand(string, null: true)に変更しました。
#WHY
メルカリの使用上、変更する必要があった為。

[WIP]Fixed DB of brand column

---

app/views/devise/sessions/new.html.haml

#WHAT
①新規会員登録ボタンを押すと、新規会員登録ページに遷移する様にしました。
②Mercariの画像を押すと、トップページに飛ぶ様にしました。
③Googleでログインの文字色を修正しました。
#WHY
本家の使用に合わせる為。

[WIP]Updated Sign_in Page

---

app/assets/stylesheets/shared/header.scss
app/controllers/products_controller.rb
app/controllers/users_controller.rb
app/views/products/_product.html.haml
app/views/products/new.html.haml
app/views/products/show.html.haml
app/views/shared/_exhibitation.html.haml
app/views/shared/_header.html.haml
app/views/shared/_navigations.html.haml
app/views/users/identification.html.haml
app/views/users/mypage.html.haml

#　What
各viewにおけるボタンに遷移先を設定
#　Why
userがアプリケーションを使用する際の利便性を向上させるため
#　Gyazo
https://gyazo.com/4b2ba679e96a2c7ba2687ec47c2e0a55 
https://gyazo.com/81e945b56802b66604d0045211e92b9f 
https://gyazo.com/7c59964df147f67af90aa0e811d93443
https://gyazo.com/c50762913adb1cb45386e8884ee77527
https://gyazo.com/d4d08c2d2ce507bce3260e1483af2db1 
https://gyazo.com/ea04f35adbd203fb59a8b2a2109c8e59 
非ログイン時　login registration btn
非ログイン時　出品ページ遷移先
非ログイン時　挙動
login registration btn遷移先
マイページからログアウト
マイページサイドバー遷移先　

Seting&makeing path

---

README.md
app/controllers/products_controller.rb
app/controllers/purchase_controller.rb
app/views/products/new.html.haml
app/views/products/show.html.haml
db/migrate/20190824022008_remove_postage_by_from_purchases.rb
db/migrate/20190824022306_add_status_to_products.rb
db/schema.rb

DB修正とそれに伴う変更、デバッグ
- DB修正
- statusをproductsテーブルに移動
- purchasesテーブルから不要なカラムを消去
- README更新
- 商品出品時にstatusを初期化
- 商品購入時にstatusを1（売却済）に変更
カラムを適切なテーブルに配置するため

Change database tables

---

app/views/products/_searchbar.html.haml

カテゴリーデータの修正。
ユーザーが商品を正しく選択できるようにするため。

adjust search.html.haml

---

Gemfile
Gemfile.lock
app/views/devise/sessions/new.html.haml
app/views/profile/edit.html.haml
app/views/shared/_navigations.html.haml
app/views/users/sign_out.html.haml
db/schema.rb
spec/factories/users.rb
spec/features/login_helper_spec.rb
spec/features/logout_helper_spec.rb
spec/features/profile_helper_spec.rb
spec/rails_helper.rb

#What 
テストコードを作成しました。
①ログインページ
②サインアウトページ
③プロフィールページ
#Why
動的ページの挙動を事前に確認する為。

[WIP]Created test codes

---

app/controllers/users/omniauth_callbacks_controller.rb
app/views/devise/sessions/new.html.haml

#What
SNSログインについて、一部修正を行なった。
①SNSを経由して、エラーメッセージを表示する元のページに戻る。
②本番環境ではroot_pathに移動。
https://gyazo.com/fb9e5b694414ba7bb65403348c869823
#Why
SNSログインのコードに修正すべき点があった為。

[WIP]Updated SNS log in

---

app/controllers/application_controller.rb
config/deploy/production.rb

Basic認証を実装
現状は誰でもアクセスできてしまう状態なので、ユーザー名とパスワードを共有している者だけにアクセスを制限するため

Implement basic authentication

---

app/views/devise/sessions/new.html.haml
app/views/products/new.html.haml

#What 
①SNSログインについて、本番環境と開発環境でリンク先を分けた。
②出品ページのモーダルに出るリンク先をトップページに変更。
#Why
①コードに不備があった為、修正した。
②元はメルカリ本家に飛ぶ様になっていた為、修正した。

[WIP]SNS login + Link

---

app/views/devise/sessions/new.html.haml

#WHAT 
ログイン画面のビューの崩れを修正しました。
#WHY
ビューが崩れていた為。

Fixed indents
